server/automated_tests_server.rb
testers/markus_utils.py
testers/sql/client/script.py
testers/uam/client/script.py

Markus related change: MarkUsProject/Markus#2900

Add group repo name to autotest protocol

---

README.md
server/automated_tests_server.rb

MarkusProject/Markus#3171
MarkusProject/Markus#3172
MarkusProject/Markus#3175

Update server to work with latest Markus 1.6.0

---

server/automated_tests_server.rb

makes sure a meaningful error is sent back to Markus to be displayed if there is an error for any reason

fix silent failure

---

README.md

Finish documentation

---

server/autotest_enqueuer.py
server/autotest_server.py

This will be used to update expected completion times for batches of jobs in Markus

Report the actual time a job waited to be processed

---

server/autotest_enqueuer.py

If the enqueuer script raises as error after files have been copied from Markus (whether for testing or for uploading new tester scripts), theses files would be stranded and never cleaned up.
This makes sure that these files are cleaned up even if an error is raised.

Clean up directories copied from Markus after enqueuer error

---

install.sh
server/autotest_server.py
server/rq_fail_queue_contents.py
testers/create_test_env.sh

correctly join api url used to return results and make sure lib path is setup correctly when creating virtual environments

Production bugfixes

---

install.sh

now goes to the workspace directory so log files are written there and deactivates (just in case)

update crontab suggestion

---

server/autotest_server.py

quote killall command properly and kill by process group differently if we are running with multiple users

fix bugs in how we kill user processes when the script times out

---

testers/python/server/markus_python_tester.py

This is a quick implementation. Further updates are required both here and on the Markus side (see #122)

python-tester: concatenate description (docstring) to test name

---

server/requirements.txt

Unpin redis version

---

.gitignore
server/autotest_enqueuer.py
server/bin/archive_workspace.sh
server/bin/install.sh
server/bin/uninstall.sh
testers/testers/haskell/bin/install.sh
testers/testers/haskell/bin/uninstall.sh
testers/testers/java/bin/install.sh
testers/testers/java/bin/uninstall.sh
testers/testers/jdbc/bin/install.sh
testers/testers/jdbc/bin/uninstall.sh
testers/testers/py/bin/install.sh
testers/testers/py/bin/uninstall.sh
testers/testers/pyta/bin/install.sh
testers/testers/pyta/bin/uninstall.sh
testers/testers/racket/bin/install.sh
testers/testers/racket/bin/uninstall.sh
testers/testers/sql/bin/install.sh
testers/testers/sql/bin/uninstall.sh

* add uninstall and archive scripts for the server
* add uninstall scripts for each tester
* add function to `autotest_enqueuer.py` prints a list of all installed testers
(All PRs labeled with the name "Autotest future" should be pulled in in order)

Autotest future (Part 3): query installed testers and add ability to uninstall testers

---

server/autotest_server.py
server/bin/tester_schema_skeleton.json
server/hooks_context/builtin_hooks.py
server/hooks_context/hooks_context.py
server/hooks_context/utils.py
testers/testers/custom/bin/default_hooks.py

Introduces the `hooks_context` package containing all code related to executing hooks around tests.
For a more detailed explanation of the mechanism used to run hooks, see the docstring for the `Hooks` class in `server/hooks_context/hooks_context.py` and the docstring for the `Hooks.around` context manager method in the same file.

autotest-future: builtin-hooks

---

server/bin/requirements.txt

version 4 now supports python 3

Use stable version of supervisor

---

server/autotest_enqueuer.py
server/bin/requirements.txt
server/form_validation/__init__.py

- use the `jsonschema` library to add defaults to form data before validation

Form defaults and validation

---

testers/testers/java/lib/build.gradle

java: Revert sourceCompatibility to 1.8.

---

server/autotest_server.py
server/config.py

- this allows us to test/develop in an environment that is more similar to production

Use multiple tester users in development

---

server/autotest_enqueuer.py
server/bin/tester_schema_skeleton.json
server/hooks_context/builtin_hooks.py
testers/testers/custom/specs/settings_schema.json
testers/testers/haskell/specs/settings_schema.json
testers/testers/java/specs/settings_schema.json
testers/testers/jdbc/specs/settings_schema.json
testers/testers/py/specs/settings_schema.json
testers/testers/pyta/markus_pyta_tester.py
testers/testers/pyta/specs/settings_schema.json
testers/testers/racket/specs/settings_schema.json
testers/testers/sql/specs/settings_schema.json

Add titles to many attributes. Add some missing types. Ensure that tester
schemas are sorted alphabetically.

specs: Tweak some tester schemas.

---

.travis.yml
testers/testers/py/lib/sql_helper.py
testers/testers/py/tests/script_files/data1.sql
testers/testers/py/tests/script_files/data2.sql
testers/testers/py/tests/script_files/schema.ddl
testers/testers/py/tests/script_files/test_sql.py
testers/testers/py/tests/student_files/submission.sql

- add helper script to run sql tests in python on markus

Sql helper

---

server/config.py

- I should never have removed this in the first place...my bad.

Add back rlimit settings in config

---

Layerfile
README.md

This will run tests automatically on every commit once authorized
See: https://layerci.com/run?id=129

Add Layerfile

---

server/autotest_server.py

- an update on #229 in order to make student directories writable/removable

Make student directories editable

---

src/autotester/cli.py
src/autotester/config.py
src/autotester/exceptions.py
src/autotester/resources/ports/__init__.py
src/autotester/resources/postgresql/__init__.py
src/autotester/server/hooks_context/builtin_hooks.py
src/autotester/server/hooks_context/hooks_context.py
src/autotester/server/server.py
src/autotester/server/utils/file_management.py
src/autotester/server/utils/form_validation.py
src/autotester/server/utils/path_management.py
src/autotester/server/utils/redis_management.py
src/autotester/server/utils/resource_management.py
src/autotester/server/utils/string_management.py
src/autotester/server/utils/user_management.py
src/autotester/testers/custom/default_hooks.py
src/autotester/testers/custom/markus_custom_tester.py
src/autotester/testers/haskell/markus_haskell_tester.py
src/autotester/testers/java/markus_java_tester.py
src/autotester/testers/markus_test_specs.py
src/autotester/testers/markus_tester.py
src/autotester/testers/py/markus_python_tester.py
src/autotester/testers/pyta/markus_pyta_tester.py
src/autotester/testers/racket/markus_racket_tester.py
src/autotester/tests/cli_test.py

This PR did not update:
- class and module docstrings
- test files and helper files (`c_helper.py` and `sql_helper.py`)
Those should be added in later PRs

Make sure all python methods/functions have type annotations and docstrings

---

bin/install.sh
src/autotester/server/server.py
src/autotester/server/utils/resource_management.py

- add the server user to all user worker groups
- account for infinite/unset rlimits when adjusting rlimits before test runs
- kill worker processes in a shell

Docker bugfixes: groups, rlimits, shells!

---

src/autotester/testers/custom/tests/script_files/autotest_01.sh
src/autotester/testers/custom/tests/student_files/submission.py

It seems the Docker image we're using doesn't have python (2) installed by default, and we aren't installing it in our setup.

custom-tester: Update test files to use python3.

---

src/autotester/server/utils/file_management.py
src/autotester/server/utils/tests/file_management_test.py

Added tests for file_management.py
To Do:
Add tests for setup_files. 
Add tests for fd_lock

test: Added tests for file_management

---

src/autotester/server/utils/tests/path_management_test.py

Added tests for path_management.py

test: Added tests for path_management

---

src/autotester/server/utils/tests/test_file_management.py
src/autotester/server/utils/tests/test_setup_files.py

Added tests for setup_files method in file_management.py

test: Added test for setup_files in file_management.py

---

src/autotester/server/client_customizations/markus.py
src/autotester/server/utils/file_management.py

- Fixes a bug where nested directories passed to the autotester in zip files were not being extracted properly

Unzip subdirectories properly

---

Changelog.md
src/autotester/cli.py

copy of #265 for v1.10.1-rc

---

setup.py
src/autotester/server/client_customizations/markus.py

- new version can handle uploading binary files
- upload all files as binary data

Update to new version of markus-api

---

README.md
client/autotest_client/__init__.py
client/autotest_client/tests/test_flask_app.py
server/autotest_server/__init__.py
server/autotest_server/testers/java/setup.py
server/autotest_server/testers/py/requirements.txt
server/autotest_server/testers/py/setup.py
server/autotest_server/testers/pyta/setup.py
server/autotest_server/tests/test_autotest_server.py

- update README
- improve error handling in client 
- improve tester setup for java, py, pyta by updating version, ensuring cleaner virtual environments
- style updates

Various updates

---

server/autotest_server/testers/pyta/pyta_tester.py

Previously, the pyta tester did not report the plain output as a feedback file.

Write output to feedback file for pyta

---

server/autotest_server/testers/jupyter/lib/jupyter_pytest_plugin.py

This pull request fixes a bug in the Jupyter pytest plugin when reporting failures (`IpynbItem.repr_failure`). It seems that when an `OSError` is raised, at least one of the corresponding traceback entries has `tb.frame.code.path` being a `LocalPath` instead of a `str`, which our current implementation doesn't handle.
This error had a side-effect of interrupting the remaining reporting of test results, so I've also wrapped the whole method in a try-except to prevent unhandled exceptions interrupting test result reporting in the future.

jupyter-tester: Fix bug when traceback entry path is not a string

---

.flake8
.flake8.ini
.git-blame-ignore-revs
.hound.yml
.pre-commit-config.yaml
client/autotest_client/__init__.py
client/autotest_client/tests/test_flask_app.py
pyproject.toml
server/autotest_server/__init__.py
server/autotest_server/testers/custom/setup.py
server/autotest_server/testers/haskell/setup.py
server/autotest_server/testers/java/setup.py
server/autotest_server/testers/jupyter/jupyter_tester.py
server/autotest_server/testers/jupyter/lib/jupyter_pytest_plugin.py
server/autotest_server/testers/jupyter/setup.py
server/autotest_server/testers/py/setup.py
server/autotest_server/testers/pyta/pyta_tester.py
server/autotest_server/testers/pyta/setup.py
server/autotest_server/testers/r/r_tester.py
server/autotest_server/testers/r/setup.py
server/autotest_server/testers/racket/setup.py

- install pre-commit hooks for flake8 and black
- do initial run of these hooks to clean up code
- add .git-blame-ignore-revs file to ignore changes made by the initial hook run when doing git-blames

Install pre-commit hooks for flake8 and black

---

Changelog.md
server/autotest_server/testers/pyta/pyta_tester.py
server/autotest_server/testers/pyta/requirements.txt

Also updates keys from the json reporter in the pyta tester.

Update pyta tester to use version 2.3.2

---

client/requirements.txt

Pins Werkzeug to 2.3.7 to avoid issues with Wekzeug 3.0

pin Werkzeug==2.3.7

---

server/autotest_server/testers/pyta/requirements.txt

updated to python-ta v2.6.3

---

server/autotest_server/testers/pyta/requirements.txt

update python-ta version to 2.7.0

update python-ta version to 2.7.0

---

Changelog.md

update changelog with new release v2.4.1

---

Changelog.md

update changelog for v2.4.2

---

.github/workflows/test_ci.yml

Testing to see if CI passes with the inclusion of typing-extensions

add typing-extensions to test venv

---

Changelog.md

update changelog with new release v2.4.3

---

Changelog.md

Update the changelog for v2.4.4

update changelog for v2.4.4

---

Changelog.md

Changelog: update changelog for v2.5.0

---

Changelog.md

Update changelog for version 2.5.1

---

Changelog.md

Changelog update for v2.5.2

---

Changelog.md
server/.dockerfiles/Dockerfile
server/autotest_server/testers/jupyter/setup.py
server/autotest_server/testers/py/setup.py
server/autotest_server/testers/pyta/setup.py

The python versions listed in the docker file was cleaned up by removing versions 3.8 to 3.10 and adding 3.13.

update python versions in docker file

---

Changelog.md

update changelog with new release v2.6.0

---

Changelog.md

update changelog with new release v2.7.0

---

Changelog.md

update changelog with new release v2.8.0

---

Changelog.md

update changelog with new release v2.8.1
