MarkUsProject/markus-autotesting

- .gitignore
- testers/uam/server/pam_wrapper.py
This fixes pam to be invoked within the same virtualenv of the invoking script.
> Use same python script executable when invoking pam

- testers/markusapi.py
@adisandro I added a route to enable users to upload annotations through the API. These changes are updates to the wrapper.
Note that I wanted to upload JSON data, so I changed `submit_request`. I'm not sure if there's another way to do that.
> markusapi: write method for uploading annotations

- testers/python/client/script.py
- testers/python/install.sh
- testers/python/requirements.txt
- testers/python/specs.json
* Increase default global timeout to 1 hour and hide it (to use Markus' native one)
* Install timeout-decorator by default and add info to the test script
> Python tester timeout changes

- server/automated_tests_server.rb
- also add <marks_total> tag to timeout output
> Fix timeout: enforce timeout by killing threads that read stderr/stdout

- server/automated_tests_server.rb
@mishaschwartz we totally forgot that we're no longer reading with IO#gets, we don't strip the original newlines
> Remove extra \n when appending to stdout and stderr

- server/automated_tests_server.rb
- testers/markus_tester.py
Ensures result xml ends with a newline so automated_test_server.rb will reliably process the last line of the result (this may cause xml parsing errors later on otherwise)
> xml format: add newline to end of result xml

- server/monitor_redis.sh
bash script to check if a resque worker has stalled and if so sends an email warning (should be run regularly from a cronjob)
> monitor: check if resque worker is stalled

- .gitignore
- install.sh
- server/start_resque.sh
- server/stop_resque.sh
This is the markus-autotesting side of harmonizing a default installation of Markus+markus-autotesting.
(see MarkUsProject/Markus#3336)
The installation can now work for all environments (dev|test|prod) and travis-ci builds.
> Harmonize Markus and markus-autotesting defaults

- install.sh
This makes the script consistent with the Vagrant provisioning scripts on MarkUs.
Turns out if `.bash_profile` exists, `.profile` won't execute. If @adisandro/@mishaschwartz really want to use `.bash_profile` for your own environments, I can change the MarkUs provisioning scripts instead, but I'm merging this in for now.
> rq: Update install.sh to use .profile

- install.sh
- server/autotest_server.py
- server/config.py
- server/kill_worker_procs.c
This is an attempt to implement the strategy for killing potentially malicious code described in this article: https://lwn.net/Articles/754980/
* for every tester user, we now also create a reaper user whose sole job is to kill the tester user's processes
* these processes are killed using the `kill_worker_procs` executable (compiled at install time and copied for each use). See the article (above) for an explanation on how the various permission settings on this file let us safely kill worker processes
* also introduces a way to set rlimit limits for tester users. These limits are also manipulated to ensure the reaper can always kill the tester's processes. 
* fixes a bug where a tester user could only do a single test run in their working directory before changes to that directory's …
> Kill student code more securely

- server/generate_supervisord_conf.py
fix syntax error in supervisord.conf file that was causing supervisor processes not to be created properly
> fix syntax error in supervisor config file

- server/autotest_enqueuer.py
- server/autotest_server.py
generalize shebang from python3.X to python3 and rely on venv to specify correct python3 version
> Generalize python3 version in shebang

- server/autotest_enqueuer.py
rename function so that it doesn't clash with variable names and the function name is more descriptive
> rq-job-id function rename

- testers/haskell/client/Test.hs
- testers/haskell/install.sh
- testers/haskell/server/markus_haskell_tester.py
- testers/haskell/specs.json
Allows us to configure the GHC_PACKAGE_PATH variable that all haskell test commands use using the specs file. This makes it potentially configurable for each instance separately. 
Updates the haskell install script to install cabal packages globally (probably not best practice in the long run but good enough until we come up with something better)
> configure GHC_PACKAGE_PATH using specs

- testers/racket/server/markus_racket_tester.py
* don't treat any stderr output as a true error
* skip empty stdout instead of raising errors
> Better error messages in racket tester

- testers/python/server/markus_python_tester.py
- testers/python/specs.json
This allows us to run python tests using an older python version (ie. python2.x)
> Allow pytest tests to be run using an arbitrary virtual environment

- testers/haskell/server/markus_haskell_tester.py
This allows stderr to be reported as extra_info back to MarkUs
> Don't redirect stderr for haskell tester

- server/autotest_server.py
don't display a hook error if the hooks file doesn't exist or the hooks file doesn't contain the right function
> hook errors should only be for real errors

- testers/python/client/script.py
- testers/python/server/markus_python_tester.py
- testers/python/specs.json
* don't do tester discovery 
* allow for configurable test output for unittest and pytest
* added the following spec options for the python tester:
* [pytest_tb_format](https://pytest.readthedocs.io/en/2.1.0/usage.html#modifying-python-traceback-printing)
* [unittest_verbosity](https://stackoverflow.com/a/1322648/5992438)
* tester (either `'pytest'` or `'unittest'`)
> Make python tester verbosity configurable

- testers/python/server/lib/c_helper.py
* convert CRLF line endings to LF
* add `make_args` class attribute to the `TestExecutable` class, these additional arguments will be passed to the `make` command when compiling source code.  
* for example, if you want to specify which `Makefile` to use you can set:
```python
from c_helper import TestExecutable
class MyTestClass(TestExecutable):
make_args = ['-f', 'mymakefile']
...
```
> c helper: compile with additional arguments

- testers/python/server/lib/c_helper.py
This change was made in a previous version of this library but did not make it into the version that was added here.
> Allow long running ltrace tests to return partial results

- server/requirements.txt
unpin redis from version < 3.0 now that rq has updated their code (see https://github.com/rq/rq/pull/1016)
> Unpin redis version

- testers/python/server/markus_python_tester.py
This was trying to use a deprecated (and removed) function
> Fix bug that occurs when determining which tester to run

- testers/testers/jdbc/bin/create_environment.sh
- testers/testers/jdbc/bin/destroy_environment.sh
- testers/testers/jdbc/specs/default_environment_settings.json
- testers/testers/jdbc/specs/default_settings.json
- testers/testers/jdbc/specs/environment_ignore.yml
- testers/testers/jdbc/specs/environment_settings.yml
- testers/testers/jdbc/specs/settings.yml
- testers/testers/sql/bin/create_environment.sh
- testers/testers/sql/bin/destroy_environment.sh
- testers/testers/sql/specs/default_environment_settings.json
- testers/testers/sql/specs/default_settings.json
- testers/testers/sql/specs/environment_ignore.yml
- testers/testers/sql/specs/environment_settings.yml
- testers/testers/sql/specs/settings.yml
This updates the specs for both the sql and jdbc testers so that they are more in line with the specs for other testers. Specifically, this introduces the idea of a true "runnable group" for these testers which is distinct from the solutions that were created at environment creation time. This will allow users to select a subset of the tests to run (if desired). 
(All PRs labeled with the name "Autotest future" should be pulled in in order)
> Autotest future (Part 7): unify specs for sql and jdbc testers

- server/autotest_enqueuer.py
- server/autotest_server.py
- server/bin/install.sh
- server/bin/tester_schema_skeleton.json
- server/tests/autotest_enqueuer_test.py
Introduces changes to installation/server/enqueuer required to pass settings in json-schema format and automatically update/create tester environments.
Also introduces a json schema that can be used as a skeleton and filled in with the settings from installed testers when requested through the autotest_enqueuer.
> autotest-future: changes to server, enqueuer, and main installation

- testers/testers/markus_test_specs.py
- testers/testers/markus_tester.py
Changes to MarkusTester/MarkusTest/MarkusTestSpecs required to pass settings in json-schema format and automatically update/create tester environments.
This PR should be tested in conjunction with https://github.com/MarkUsProject/Markus/pull/3875 on the MarkUs side and with #167.
> autotest-future: changes to the markus tester base classes and the markus tester specs class

- server/autotest_server.py
- testers/testers/markus_tester.py
- report full traceback message when reporting a test or tester error
- also don't require a `test_group_id` when sending back group results to MarkUs
> Better error messages

- server/autotest_server.py
- server/bin/tester_schema_skeleton.json
- testers/testers/custom/markus_custom_tester.py
- testers/testers/custom/specs/settings_schema.json
- testers/testers/haskell/markus_haskell_tester.py
- testers/testers/haskell/specs/settings_schema.json
- testers/testers/java/markus_java_tester.py
- testers/testers/java/specs/settings_schema.json
- testers/testers/py/markus_python_tester.py
- testers/testers/py/specs/settings_schema.json
- testers/testers/pyta/markus_pyta_tester.py
- testers/testers/pyta/specs/settings_schema.json
- testers/testers/racket/markus_racket_tester.py
- testers/testers/racket/specs/settings_schema.json
- use `extra_info` exclusively (not `extra_data`)
- update the tester schemas to be consistent (don't require keys that aren't there, set defaults where necessary, etc.)
This is a companion PR to #182 because it sets the defaults.
This should be tested with https://github.com/MarkUsProject/Markus/pull/3954
> Update tester schema settings

- .flake8.ini
- .hound.yml
- add config file for flake8 (used by houndci)
- see [here](http://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-max-line-length) for more possible config options
> flake8 config

- server/autotest_server.py
- server/bin/install.sh
- server/config.py
- server/generate_supervisord_conf.py
- assign one tester user per rq worker
- warns if there are not enough users to create all the workers in `config.WORKERS`
> Merge rq workers and users

- testers/testers/java/lib/gradlew
By setting the maximum/minimum heap size for JVM, the `./gradlew installDist --no-daemon` command in the java tester install script hangs.
It doesn't hang if the maximum heap size is increased to something like:
```
DEFAULT_JVM_OPTS='"-Xmx128m" "-Xms128m"'
```
but I think it's probably safest if we just stick with the [defaults](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:how_much_memory_does_the_daemon_use_and_can_i_give_it_more)
> Fix java hang on install

- testers/testers/haskell/markus_haskell_tester.py
- testers/testers/java/markus_java_tester.py
- testers/testers/jdbc/markus_jdbc_tester.py
- testers/testers/markus_tester.py
- testers/testers/py/markus_python_tester.py
- testers/testers/pyta/markus_pyta_tester.py
- testers/testers/racket/markus_racket_tester.py
- testers/testers/sql/markus_sql_tester.py
- this simplifies the default interface to the `open_feedback` context manager so that you don't have to pass in the filename of your feedback file every time.
> Feedback file context manager interface simplification

- server/autotest_server.py
- fix typo in variable name introduced in #185 
- make sure to decode strings from redis
> Typo and decode quick fix

- testers/testers/haskell/markus_haskell_tester.py
- testers/testers/java/markus_java_tester.py
- testers/testers/jdbc/markus_jdbc_tester.py
- testers/testers/markus_tester.py
- testers/testers/racket/markus_racket_tester.py
- testers/testers/sql/markus_sql_tester.py
- this makes sure that only the relevant information is communicated in the test results
- the only time a traceback should be included in the results is if the error is an error in the markus-autotesting code, not in the test scripts, student files, etc.
Closes #193
> Don't print full traceback if the error is expected

- server/bin/uninstall.sh
Postgres doesn't like it if you drop a database on a line with multiple statements.
Explanation: https://dba.stackexchange.com/a/21487
> Drop db in single line

- server/autotest_enqueuer.py
An error still gets raised without this but it is less informative since the error message that is raised otherwise warns about the job timeout for `rq` being zero.
> Raise an error if there are no tests to run in the given category

- server/autotest_server.py
- not specifying a hostname (even if we specify `localhost`) means that postgres/psycopg2 will try to connect to the database using the unix-domain socket apparently.
- this can cause issues if postgres is not set to listen on the socket
> Make sure postgres uses tcp port

- testers/testers/py/bin/create_environment.sh
- this will be handled differently on the master branch (use the latest version of pytest and update the way we parse the junitxml file).
> Fix pytest version to before the junitxml output file format was changed

- README.md
- server/autotest_enqueuer.py
- server/config.py
This enables better reporting of errors back to MarkUs during test script updates and test cancelation
> Remove service queue

- testers/testers/py/bin/create_environment.sh
- testers/testers/pyta/bin/create_environment.sh
- an out of date pip version causes a non-zero error code which causes the script to abort
> Upgrade pip before install

- server/autotest_server.py
- file permissions for student files should be `rw-rw-rw-` so that test files can move/replace/modify them while the tests are running
- ~~file permissions should be `rw-rw----` for student files as long as files are group owned by the test user~~
- ~~all other file/dir permissions should be `---` for 'other' users as long as everything is group owned by the test user~~
- we can't `chown` if we are not root so we can't update ownership on the fly
> Set file permissions for student files

- testers/testers/custom/markus_custom_tester.py
- testers/testers/haskell/markus_haskell_tester.py
- testers/testers/markus_tester.py
- testers/testers/racket/markus_racket_tester.py
- only mark unexpected tests as having an `'error_all'` status
- this will mean that MarkUs will not stop parsing test results if an expected error is raised
- mark test file compilation/discovery errors as expected
> Differentiate between expected and unexpected tester errors

- Changelog.md
- server/autotest_server.py
- allow tests to write to existing subdirectories but not overwrite existing test script files
> Make subdirectories writeable in test workspace

- .dockerfiles/Dockerfile
- .dockerfiles/entrypoint-dev.sh
- .dockerignore
- .gitignore
- Changelog.md
- bin/install.sh
- bin/start-stop.sh
- docker-compose.yml
- src/autotester/resources/postgresql/__init__.py
- src/autotester/server/server.py
- src/autotester/server/utils/user_management.py
- src/autotester/testers/custom/bin/install.sh
- src/autotester/testers/haskell/bin/install.sh
- src/autotester/testers/java/bin/install.sh
- src/autotester/testers/py/bin/install.sh
- src/autotester/testers/pyta/bin/install.sh
- src/autotester/testers/racket/bin/install.sh
- uses the `markus_dev` bridge network which is shared with the MarkUs `rails` service
- set up ssh server on the `autotest` service (and install rsync for passing files from MarkUs)
- introduce `.dockerignore` file to reduce build footprint
- set environment variables in `.bash_profile` and source them before running the `autotest_enqueuer` command (required because MarkUs connects with the `Net::SSH` gem which does not source any of `.profile`, `.bash_profile`, `.bashrc`)
- automatically pass MarkUs' rsa public key using a volume (`ssh_pub_key`)
- use `PGHOST` environment variable to set postgres hostname
- allow for null reaper user
- make sure environment variables are passed to process that is generating `supervisord.conf` file
- allow installation of testers non-interactively
TODO: …
> Docker: connect to MarkUs containers

- docker-compose.yml
This is same like #4385 in MarkUsProject/Markus
when we try to start up postgres it raises the following error
**Error** : Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD for the superuser. Use
"-e POSTGRES_PASSWORD=password" to set it in "docker run".
You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
without a password.
**Change:**
Added the POSTGRES_HOST_AUTH_METHOD=trust
> Docker: Added new env variable in postgres image

- Layerfile
- the base image in the layer file must now be specified by prefixing the image name with `vm/`
- checkpoints happen automatically and are no longer required
> Update layerfile to use new syntax

- src/autotester/server/server.py
- src/autotester/server/utils/file_management.py
- this is required to allow the server user to have enough permissions to copy files and clean up the work directory, while simultaneously only giving one specific tester user permission to read/write/execute a file/directory.
> Chown test files to be group owned by test user

- src/autotester/cli.py
- src/autotester/tests/cli_test.py
- Don't show full traceback for a validation error (it's already confusing enough as it is for the user)
- As a side note, [rjsf](https://github.com/rjsf-team/react-jsonschema-form) still doesn't fill in our defaults properly by itself (it looks like because the `oneOf` types are [mostly but not fully supported](https://react-jsonschema-form.readthedocs.io/en/latest/#q-does-rjsf-support-oneof-anyof-multiple-types-in-an-array-etc)) so we still need to fill in defaults and validate in the autotester itself.
> Treat validation error message like an expected error

- src/autotester/server/utils/path_management.py
Issue:
In path_management.py when we try to append path into sys.path it temporarily add path and finally it has to delete it but it is not deleting properly. We are not actually using this anywhere else in the code so it wasn't an issue before.
Fix:
Modified the method add_path, now it will work for both append and prepend.
> Fix: Modified path_management.py

- bin/install.sh
- bin/start-stop.sh
- docker-compose.yml
- src/autotester/server/server.py
- also add another service for rq_dashboard. you can now monitor rq jobs in your browser from `localhost:9181`
> Run supervisor process in foreground on docker

- .dockerfiles/entrypoint-dev.sh
This change means that the `.installed` file that is created to signal that the tester has already been installed in the container only exists in the container in question. This means that a new container will always run the install script.
> Docker: keep install flag inside the container

- .gitignore
- Changelog.md
- src/autotester/MANIFEST.in
- src/autotester/testers/haskell/bin/install.sh
- src/autotester/testers/haskell/lib/Stats.hs
- src/autotester/testers/haskell/markus_haskell_tester.py
The tasty-stats ingredient requires git to be installed to get data from tests that is unnecessary for our purposes. I would rather not require git for the entire project simply because the tasty-stats ingredient requires it. So instead I added our own Stats ingredient which is essentially just a paired down version of the tasty-stats ingredient.
TODO:
> Replace tasty-stats

- src/autotester/testers/haskell/haskell_tester.py
If a haskell test run returns a non-zero exit code then the partial test results were not being collected and reported properly.
This PR ensures that partial test results will still be reported regardless of the test process' exit status.
> haskell: report test results even if full test run fails

- src/autotester/testers/pyta/bin/requirements.txt
Problem:
- pyta depends on pylint which depends on isort
- isort recently put out version 5 which has breaking changes
- pylint does not support version 5 of isort so the it installs the following version `isort>=4.2.5,<5`
- pyta version 1.4.2 installs `pylint>=2.1,<2.2`
- pylint 2.1 (and 2.2 as well actually) have the following import line for `isort>=4.2.5` which means that the latest version of isort is installed (5.1.1)
- this breaks pyta version 1.4.2 and so breaks the pytest autotester when run with python3.6 or 3.7
Solution:
- force isort to not use version 5 when the tester uses python 3.6 or 3.7
> Correct version of isort for python < 3.8

- src/autotester/server/client_customizations/markus.py
MarkUs used to export zip archives in nested two levels deep (archive name, group name) but now it's only one level deep (archive name only).
This PR makes sure to only ignore the top level dir.
> markus-client: only look one level deep in zip archive instead of two

- src/autotester/resources/postgresql/__init__.py
- src/autotester/testers/py/lib/sql_helper.py
Depending on how the postgres authorization is set up. You may need to explicitly pass the host and port parameter when running `psql` commands within a test. 
Previously, we defaulted to using "localhost" and 5432 but we can't always assume that the postgres server is running at localhost and with the default port.
> Pass PGHOST and PGPORT info to tests

- src/autotester/resources/postgresql/__init__.py
- subprocess has a hard time setting the environment variables if one of the values of the dictionary passed to `Popen(...env=...)` is not a string
- this PR changes the port number to a string so that subprocess won't complain
> Env variables (including the port number) need to be a string

- setup.py
- src/autotester/testers/py/bin/requirements.txt
previous version 2.8.4 is not compatible with python3.9
> Bump pyscopg2-binary version 2.8.6

- src/autotester/testers/java/java_tester.py
Compilation errors were detected by looking for output on stderr but stderr was being redirected to stdout
> java-tester: don't suppress compilation errors

- server/start_stop.py
The supervisor log file gets written to the current directory. If start_stop.sh is run from somewhere random, the log file can be hard to find later. This makes sure that the log file gets written somewhere consistent.
> Always write supervisor log file to the same directory

- MANIFEST.in
This was left over from before when this was a self contained package
> Remove unused manifest file

- server/.dockerfiles/Dockerfile
When running the `docker-compose build autotest` command, it would wait and prompt for user input to set the timezone. This fix makes command avoid prompting for user input so build command can properly run.
> Fix docker-compose build command to avoid waiting for user input

- server/autotest_server/testers/pyta/pyta_tester.py
- server/autotest_server/testers/pyta/requirements.txt
Use pyta's new JSONReporter class to collect data from the test results instead of subclassing PositionReporter.
Note that this requires python-ta version 2.1 (which should be released soon). To test in the meantime replace this line in server/autotest_server/testers/pyta/requirements.txt:
```
python-ta==2.1.0; python_version>="3.8"
```
with 
```
git+https://github.com/pyta-uoft/pyta.git; python_version>="3.8"
```
> Update pyta tester to be compatible with pyta version 2

- server/autotest_server/__init__.py
Before, when tester environment creation failed, the error was generic and gave no info about what actually went wrong. This change means that the original error message will also be displayed.
> Improve error message so it gives some info about what went wrong

- client/autotest_client/__init__.py
Fixes small bug where no schema existing in the redis DB meant that the fallback was causing an error because it tried to load a json string that wasn't a string.
> When a schema doesn't exist, load from an actual json string

- Changelog.md
- client/autotest_client/__init__.py
This is required to check status. On very large batch jobs it can take much longer than the default (500 seconds) to retrieve a test result.
> Keep result object alive for longer 

- docker-compose.yml
- server/.dockerfiles/Dockerfile
Volumes mounted on the docker container are (now? always?) owned by root if the mount-point doesn't already exist on the container. If it does exist then the directory permissions/ownership is not changed. 
By pre-creating the mount-point we ensure that the permissions are what we want
> Workspace volume should be initially created as if owned by the login user

- client/autotest_client/__init__.py
If the api receives unexpected keyword argument, ignore it instead of raising an error
> Allow arbitrary kwargs when cancelling tests

- server/autotest_server/testers/r/lib/r_tester.R
The code under test may write to stdout which would interfere with reporting test results. This redirects stdout to /dev/null while tests are being run so that only the results themselves get reported.
> Redirect stdout for r tester

- server/autotest_server/testers/jupyter/lib/jupyter_pytest_plugin.py
Previously test cells were defined by an initial comment that started with `test` followed by zero or more word characters. This differed from the documentation that indicated that whitespace characters could also be included. This PR updates the regular expression that is used to find test cells so that whitespace (and any character really) is also accepted.
> Allow whitespace in jupyter tester definitions

- client/autotest_client/__init__.py
- client/autotest_client/tests/test_flask_app.py
There is no real need to have the client send a unique username just so we have some key to store credentials under. Clients don't know if their key is going to be unique or not and it's annoying to make them have to guess.
This PR uses the automatically generated unique api key as a key to store user credentials instead. It also makes sure that this api key is actually unique by using redis' hsetnx function (which is atomic).
> Do not require client to send their own unique username

- Changelog.md
- server/autotest_server/testers/r/lib/r_tester_setup.R
- server/autotest_server/testers/r/setup.py
Currently, the R tester accepts a list of package names from the test configuration and installs them, along with the tester's required dependencies, using `install.packages`.
This PR extends this functionality using the R [remotes](https://remotes.r-lib.org/) library to allow for installing specific package versions (using `remotes::install_version`) and from other sources like GitHub (using `remotes::install_github`). This allows more flexibility for the instructor to specify dependencies, and is required to allow us to specify `rjson == 0.2.20`, which is the last version to support R version 3.x.
Because `install.packages` doesn't raise an error or return false (or something) when an installation fails, I also included an additional check to see whether the package was actually …
> r tester: Move dependency installation into R script

- .github/dependabot.yml
Add dependabot for automatic dependency update PRs. See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates.
> dependabot: Initial commit to enable dependabot

- server/autotest_server/testers/r/lib/r_tester.R
- server/autotest_server/testers/r/r_tester.py
Previous, a test that had an error caused rjson::toJSON output to fail, resulting in no test results stored. After this change, tests with an error are recorded properly using the "error" status.
> r tester: Fix handling of tests that have an error

- client/requirements.txt
This change bumps flask to v1.1.4. MarkupSafe also needs to be pinned to a version <=2.0.1 - v2.1.0 removed soft_unicode, which is used in jinja 2.
> bump flask to 1.1.4

- server/autotest_server/testers/jupyter/lib/jupyter_pytest_plugin.py
Modifies filter on jupyter pytest plugin to catch and report syntax errors which cause notebook cells not to run as well as runtime errors. Tested in the Markus web interface. Tests to be added.
> jupyter tester: catch and report notebook syntax errors

- server/autotest_server/testers/r/lib/r_tester_setup.R
When specifying a GitHub or other remote dependency for the R tester, the URL for the package name is passed. This causes our post-install check to fail:
https://github.com/MarkUsProject/markus-autotesting/blob/7ccc3324d77eb1723bc803cb0c325c720ffaba28/server/autotest_server/testers/r/lib/r_tester_setup.R#L59-L61
`name` is bound to the URL rather than the package name. Luckily, this is pretty easily fixed because the `remotes::install_*` function family seems to return the package names from the install.
> r tester: Fix package name verification for repo sources

- server/autotest_server/__init__.py
Set ignore_root_dirs to 0 for update_test_files because markus no longer zips test files into a top level directory. Note that this is not the case for student submission files.
> set ignore_root_dirs to 0 for test files

- server/autotest_server/testers/pyta/pyta_tester.py
Previously if pyta was run on a file that does not exist, it returned a perfect score. Instead, this PR checks for the existence of the file and returns an error if it does not exist.
> bugfix: return error if pyta student file does not exist

- server/autotest_server/__init__.py
Previously feedback files were generated using time.time. This could lead to multiple feedback files with the same ID, which leads to issues. this PR creates feedback file IDs with a redis counter.
> bugfix: feedback file ids should not be time based

- client/autotest_client/__init__.py
- client/requirements.txt
- remove pinned version of markupsafe because flask v2 uses the new version of jinja (see issue solved by: #336)
- update argument in `send_file` method
> Update flask to version 2.1.2

- Changelog.md
- client/autotest_client/__init__.py
- server/autotest_server/__init__.py
This change allows clients to pass custom data to be made visible to individual test runs. This works by passing a dictionary of key/value pairs alongside the "file_url" when enqueuing a test run. The server then takes these key/value pairs and passes them to the test process as environment variables. 
This allows client applications to provide information that is visible when running tests that would otherwise not be available by just inspecting the test files and the submitted files. 
This fix is in response to this issue: https://github.com/MarkUsProject/Markus/issues/5087
> Allow client to define environment variables to pass to individual test runs

- client/autotest_client/__init__.py
Previously, if an error occurred in a command that updated a redis key containing the user's api key, the error message would contain the full text of the failed redis command. This meant that the api key was displayed in plain text to the user.
This PR fixes that by obfuscating the api_key from error messages when not in production mode. 
Also, renames "user" to "api_key" in various places because that variable name better describes the content of the variable.
> Fix security flaw where client api key was leaked as an error message

- Changelog.md
- README.md
- server/autotest_server/__init__.py
- server/start_stop.py
Test scripts that haven't been used recently can be cleaned up using the `clean` command to the `start_stop.sh` script. Users who try to run tests against these cleaned test scripts will see an error message prompting them to re-upload the test scripts again.
> Add ability to clean up test scripts that haven't been used for X days

- Changelog.md
- server/start_stop.py
Previously, if the rq executable was not in the right place then supervisord would still start up but without any rq workers actually running. This PR:
- makes a better attempt at finding the rq and supervisord execs
- makes the path to those execs configurable
- fails with an error message if either of the execs are not files or not executable
> Fail fast if rq or supervisord can't be found

- client/.flaskenv
- client/requirements.txt
- client/run.py
Remove deprecated settings after updating to flask 2.2 (most of these will be removed in 2.3 but show warnings for now)
> Update configurations for flask settings

- Changelog.md
- server/autotest_server/testers/r/lib/r_tester.R
Libraries loaded in file tested by testthat (by running the `testthat::test_file`) become available in the main namespace of the r_tester.R file. This means that if there is a conflicting name/function, the r_tester.R file may use the wrong one. 
For example, r_tester.R uses the rjson library, if a file under test loads the jsonlite library, then the `toJSON` of the jsonlite library will be used to display test results. Since jsonlite can't serialize testthat_result objects (but rjson can), an error is raised.
To avoid this, this PR uses explicit namespaces to make sure the right version of files are used. 
Note that the `rjson::` addition is necessary but the `testthat::` additions are not strictly necessary because they will always be executed before the file under test is loaded/run. …
> namespace R test runner script

- client/autotest_client/__init__.py
- client/autotest_client/tests/test_flask_app.py
- server/autotest_server/__init__.py
- server/autotest_server/tests/test_autotest_server.py
- server/install.py
- server/start_stop.py
In order to reduce the number of total redis connections used by the autotester:
- use a single redis connection by each of the API (client) processes. This is declared as a global variable
- use the _same_ redis connection used by the rq job in each worker process
- use a single redis connection in the installer script
- use a single redis connection in the start_stop script
Note that in the API, two types of connection were previously required: one that decoded all responses and another that did not. In order to use a single connection, the code that assumed that responses are decoded are updated to handle decoding as needed.
> Use a single redis connection per process

- Changelog.md
- server/autotest_server/__init__.py
- server/autotest_server/utils.py
When https://github.com/MarkUsProject/Markus/pull/6323 gets pulled in, we will no longer need to support the fact that MarkUs provides content of zip files in two different ways (one with an extra subfolder, one without).
This is one of the last steps to fully decoupling MarkUs from the autotester.
> Remove need to skip top level directories

- server/autotest_server/utils.py
.join can't accept lists as arguments so the list containing the relative path must be splatted into multiple arguments to the .join function
> Fix bug where paths were not splatted

- docker-compose.yml
Looks like the `external` network key was deprecated: https://github.com/docker/compose-cli/issues/1856.
> Update docker-compose.yml network settings

- server/autotest_server/testers/java/java_tester.py
Currently in the Java tester, failed/error tests were being detected as passing.
The problem was the condition checking for the presence of failure/error XML elements was treating XML elements with no children as falsey (see Caution under https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element).
The fix was the make an explicit `is not None` check.
> Fix handling of test failures/errors

- server/autotest_server/testers/pyta/requirements.txt
This PR simply bumps [`python-ta`](https://pypi.org/project/python-ta/#description) to the latest version,  `2.6.1`.
> bump python-ta to latest

- server/autotest_server/testers/pyta/requirements.txt
This PR bumps [`python-ta`](https://pypi.org/project/python-ta/#description) to the latest version,  `2.6.2`.
> bump python-ta to 2.6.2

- Changelog.md
- server/autotest_server/__init__.py
Previously, if a feedback file was not generated by a test run, the autotester would fail to send back test results.
I have changed this so that the autotester sends the test results but also reports the missing feedback files in an error message.
> Ensure test results are reported when feedback files are missing AB#118

- client/requirements.txt
- server/requirements.txt
Release notes: https://github.com/python-jsonschema/jsonschema/releases
Commits: https://github.com/python-jsonschema/jsonschema/compare/v4.16.0...v4.20.0
Closes #416 and closes #417.
> Bump jsonschema from 4.16.0 to 4.20.0

- .github/workflows/test_ci.yml
- Changelog.md
- README.md
- client/.dockerfiles/Dockerfile
- server/.dockerfiles/Dockerfile
- server/requirements.txt
The autotest server image now includes Python 3.7 to 3.12, and run the autotest server code using Python 3.11.
The autotest client image now includes Python 3.11, and runs the client code using that version.
> Update docker images to use Python 3.11 and include Python 3.12

- Changelog.md
- client/autotest_client/__init__.py
- server/autotest_server/__init__.py
Currently the autotester does not keep track of the status of test environment creation (mostly, installing test dependencies). In particular, a MarkUs user is able to run tests even when not all dependencies are installed, likely resulting in tests failing with some kind of "import error".
This PR introduces a new `_env_status` attribute in the Redis store for test settings to track the status of environment creation. This attribute has three possible values:
- `setup`: the environment is being set up (tests will not be run)
- `ready`: setup is complete and tests can now be run
- `error`: there was an error during environment setup (tests will not be run)
> Track test environment setup in redis

- Changelog.md
- server/autotest_server/testers/haskell/haskell_tester.py
- server/autotest_server/testers/haskell/requirements.system
- server/autotest_server/testers/haskell/setup.py
There was an issue with inconsistencies in package dependencies on the teach.cs production autotesting servers this semester. 
This pull request modifies the Haskell tester setup to use [Stack](https://docs.haskellstack.org/en/stable/), and the [lts-14.27](https://www.stackage.org/lts-14.27) snapshot to pin specific dependencies.
As a comment, lts-14.27 was chosen to be consistent with the previous Haskell installation, but it's quite old. Future work would involve upgrading dependencies to new snapshots (and versions of the GHC compiler).
> Update Haskell tester to use Stack

- server/autotest_server/testers/jupyter/setup.py
- server/autotest_server/testers/py/setup.py
- server/autotest_server/testers/pyta/setup.py
While #467 ensured that Python 3.11/3.12 are installed in development, a separate check is necessary to ensure that these versions are part of the autotest settings schema sent to MarkUs.
> Ensure that Python 3.11 and Python 3.12 are available to Python/PyTA/Jupyter testers

- Changelog.md
- server/autotest_server/__init__.py
Currently if a test group reaches the timeout limit, the test process is killed and the shell default `'Killed\n'` message is written to stderr. This is communicated as part of the test results and displayed in MarkUs.
I have replaced this error message with a more descriptive error message.
> Improve default error message when a test group times out

- Changelog.md
Update the changelog to be in line with v2.4.0
> Update changelog for release v2.4.0

- Changelog.md
- README.md
- docker-compose.yml
adds `STACK_ROOT` to the environment, which specifies the location for the `.stack` directory for the global stack install. By default this goes to the root of the workspace directory, which I think is sensible for production as well. 
Note: testing requires a rebuild of the autotester environment and running a haskelltest - after that, you should see a `.stack` location in the workspace root
> add stack_root to environment

- server/autotest_server/__init__.py
Previously, we discovered an issue with test directories with the sticky bit set. To fix it, we updated the command that changes permissions such that it explicitly unsets the sticky bit on all directories in the autotest worker directory before attempting to delete the contents of the directory, as part of other permissions changes required.
However, this prevents the standard permission changes (`ugo+rwX`) from being applied to files within directories.
This is an issue if, for example, the tests create their own files and directories and do not explicitly set them to be group executable, because anything within those directories will not be deletable by the `autotst` user.
This PR updates the sticky bit change to run as an entirely separate command.
tested against folders copied from …
> create separate sticky bit command

- Changelog.md
- client/autotest_client/__init__.py
- server/autotest_server/__init__.py
After receiving a request to create/update test settings, the autotester uses the `_env_status` key as a lock to prevent tests from being run while the environment is still being set up. (See #468)
However, because `_env_status` was being set in the server method as part of a job run, there is time between when the create/update settings request is received and the job is executed where new tests could still be run.
In the case of creating a new set of test settings, this could result in a `KeyError: _files` in the `run_tests` server method.
I've changed this so the client is responsible for setting `_env_status`, which should prevent test runs from being executed after the initial settings request is processed, regardless of when the job that sets up the test environment is created.
> Set _env_status earlier when updating settings

- server/autotest_server/tests/test_autotest_server.py
Created unit test with pytest for making sure when there is a folder with a sticky bit set, the autotester can still clean up the autotest worker's work space.
> Sticky bit unit test

- client/.dockerfiles/Dockerfile
- docker-compose.yml
- server/.dockerfiles/Dockerfile
In progress attempt at upgrading to ubuntu 22.04.
Currently running tests on 22.04 results in the following error message:
```
Messages on stderr: 
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```
> Upgrade dev docker environment to 22.04

- .github/workflows/test_ci.yml
- server/autotest_server/testers/haskell/haskell_tester.py
- server/autotest_server/testers/haskell/setup.py
- server/autotest_server/testers/haskell/stack_permissions.sh
- server/autotest_server/tests/test_autotest_server.py
Add a post-install script to update permissions on `stack` created files needed for worker users to run stack build/exec. Note that I also updated the resolver used as `16.17` is the lowest resolver compatible with ubuntu 22.04's default `ghc`. I've opened an issue about making the resolver version a setting, and I think we should make a PR to make it a setting before this PR goes into release. 
Note: there was originally a test for this change, but because the tests do not currently install all testers, it failed. We can re-add tests in a later PR where we make tests more extensive. (part of the changes for the test involved updating `test_ci.yml`. I noted that the tests were still running on ubuntu 20.04, so I updated that to 20.04. I've left that change in as it should have been in a …
> add post-install script for haskell

- server/autotest_server/__init__.py
- server/autotest_server/tests/test_autotest_server.py
Currently in some situations (such as when an autotest worker is unexpectedly killed), files can fail to be cleaned up at the end of a test run. This can result in subsequent test runs reporting an error like `[Errno 1] Operation not permitted: '/home/docker/.autotesting/workers/autotst0/__pycache__'`
However, the files are still cleaned up at the end of the test run, so subsequent test runs do not return this error.
This PR adds an attempt to clear the worker directory before setting up the assignment's files, in case there are leftover files from a previous test run.
Steps to reproduce the behavior locally:
1. In server/docker-onfig.yml comment out lines 7 onwards and restart the server so it only runs one worker (for convenience)
2. `sudo -u autotst0 -- mkdir autotst0/__pycache__`
3. …
> attempt to clean local directory before setting up test files

- Changelog.md
- server/.dockerfiles/Dockerfile
- server/autotest_server/testers/r/lib/r_tester_setup.R
Adds tidyverse as a default package for the R tester.
Note that this requires rebuilding the autotesting docker environment. Several packages are added to support tidyverse. Additionally, R is installed on build, rather than in the `install` script.  This is because in the absence of a defined timezone, the tidyverse install attempts to invoke `timedatectl`, which is not runnable by default in docker. After R is installed, the timezone from `/etc/timezone` is added to R's platform-wide `Renviron.site`, which requires root. I did try to pass the timezone as an environment variable to the R install command, but it seems like R ignores that.
> add tidyverse as a default package for the R tester

- Changelog.md
- server/autotest_server/testers/py/py_tester.py
- server/autotest_server/testers/tester.py
- server/autotest_server/tests/testers/py/fixtures/sample_tests_skip.py
- server/autotest_server/tests/testers/py/fixtures/sample_tests_success.py
- server/autotest_server/tests/testers/py/test_py_tester.py
Previously, the Python tester reported skipped tests as "passed".
I've also added a few simple test cases for the Python tester (to be expanded in the future).
Test this by using [`pytest.mark.skip`](https://docs.pytest.org/en/6.2.x/skipping.html#skipping-test-functions) on a Python test case run through MarkUs.
> Ensure Python tester omits skipped tests

- .github/workflows/test_ci.yml
- Changelog.md
- server/autotest_server/__init__.py
- server/autotest_server/tests/fixtures/test_config.yml
- server/autotest_server/tests/test_autotest_server.py
In some cases, the autotester will create files in `/tmp` during test runs. Currently these are not automatically removed, leading to issues when `/tmp` becomes full. This PR adds a cleanup of the `/tmp` directory during test teardown. All files and directories belonging to the current user will be removed at the end of tests.
> clear files created in tmp after test runs

- Changelog.md
- server/autotest_server/testers/pyta/requirements.txt
- server/autotest_server/testers/pyta/settings_schema.json
- server/autotest_server/testers/pyta/setup.py
**Proposed Changes:**
Make PyTA version a setting in the test settings for instructors to configure.
**Note:**
Python version 3.8 will be reaching end of like Oct 2024 (https://devguide.python.org/versions/). I have removed the following from the requirements.txt file and set it as a default for 2.7.0 in the setup.py file:
```
python-ta==1.4.2;python_version<"3.8"
python-ta==2.7.0; python_version>="3.8"
```
**Testing procedure:**
1. Rebuild schema: we have a new field "PyTA version"
2. Save the PyTA Automated Test settings
3. Run a submission for a PyTA assignment to see if it is successful
> Make PyTA version a setting

- Changelog.md
- server/.dockerfiles/Dockerfile
- server/autotest_server/__init__.py
- server/autotest_server/testers/r/r_tester.py
- server/autotest_server/testers/r/setup.py
Based on some instructor and TA feedback, I've made two updates to the R tester:
1. Display R package installation stderr if the installation fails. _Note_: this change generalizes to all testers whose `create_environment` setup function raises an error, but only when there is information printed to stderr.
2. Do not display the testthat result `message` field if the test passes. This field is always an error message, even when the test passes, and so should only be displayed on a test failure/error.
During the testing process, I found that tidyverse needed another package, `libxml2-dev`, to be installed, and so I added it to the server Dockerfile.
> R tester improvements

- .pre-commit-config.yaml
- Changelog.md
- client/requirements.txt
- server/.dockerfiles/Dockerfile
- server/autotest_server/__init__.py
- server/autotest_server/testers/pyta/requirements.txt
- server/autotest_server/testers/pyta/settings_schema.json
- server/autotest_server/testers/pyta/setup.py
- server/autotest_server/testers/r/lib/r_tester_setup.R
- server/autotest_server/testers/r/r_tester.py
- server/autotest_server/testers/r/setup.py
- server/requirements.txt
> Release v2.5.0

- Changelog.md
- server/autotest_server/testers/haskell/haskell_tester.py
**Description:**
When running Haskell tests within a file, and there is at least 1 failed tests, all tests fail in the file even though some of them or passing. The issue is If any test case fails, the **stack runghc** ... command will have an exit status of 1, not 0. This will cause the subprocess.run call to raise an error, because of the check=True argument.
**Solution:**
A try-except block was used around the subprocess.run call. If the return code is 1 we won't raise an error but will still raise it for other errors.
**Testing**
Currently markus-autotesting does not have a framework to do unit-testing for Haskell, and due to time, I did not write unit tests for this. 
However, to do a manual test, I used a Haskell test file that has 1 passing and 1 failing test case where I named the …
> Ensure all Haskell test cases still run within same file when there are failed test cases

- Changelog.md
- server/autotest_server/testers/haskell/haskell_tester.py
**Description:**
This Pull Request allows Haskel Tests to display compilation errors. 
**Testing Steps:**
1. Ensure test file imports student's submission file
2. Add a syntax error to the student's file 
3. Collect and run tests
4. The test results will output the compilation error
> Haskell Tests - allow displaying of compilation errors

- Changelog.md
- client/autotest_client/__init__.py
- client/autotest_client/tests/test_flask_app.py
Description:
We want to have notification when Gunicorn is down/hanging for autotesters. Created an API route, `/index`, that will be called continually to see if there is a HTTP Status 200 response.
> Add index api for monitoring if Gunicorn is down

- Changelog.md
- server/autotest_server/testers/jupyter/settings_schema.json
- server/autotest_server/testers/jupyter/setup.py
- server/autotest_server/testers/py/settings_schema.json
- server/autotest_server/testers/py/setup.py
- server/autotest_server/testers/pyta/settings_schema.json
- server/autotest_server/testers/pyta/setup.py
**Changes**:
- Change the Python autotester settings schema to include an optional field for a requirements file
- The Python autotester setup will find the requirements file from the test files and install those packages
**Testing Procedure**
- Rebuild schema and enter a Python assignment. The Python environment section will have a new field: Package requirements file
- Add a requirements file with NumPy and add a test file which uses NumPy.
- Save the settings and run tests
- With the correct requirements file name provided, the NumPy test passes
- With an incorrect requirements file name provided, the tests do not start
- With no requirements file name provided, the NumPy test fails
> Update python tester to allow a requirements file

- Changelog.md
- compose.yaml
- server/autotest_server/testers/r/lib/r_renv_setup.R
- server/autotest_server/testers/r/settings_schema.json
- server/autotest_server/testers/r/setup.py
Description:
- Users can provide package dependencies for the R autotester environment by uploading a renv.lock file in addition to manually listing dependencies (existing functionality)
Changes: 
- Updated json schema to include checkbox where users specify if renv.lock file has been uploaded 
- When creating the testing environment, an R script will install the packages in the renv.lock file using renv library if the user chooses
Testing procedure:
- Rebuild schema
- Upload dependencies through renv.lock file and click checkbox, manually list package requirements, or both
- Save the R Automated Test setttings
- Run a submission for R assignment to see if successful
Tests Conducted:
- Uploading one dependency through all use cases: knitr package was 1) entered manually as a package …
> Update R Tester to allow renv.lock file upload 

- server/autotest_server/__init__.py
Changes:
- This PR changes the results parser to add tags and overall comments from a test's standard output to its results
- Uses the changes in this PR: [https://github.com/MarkUsProject/Markus/pull/7387](https://github.com/MarkUsProject/Markus/pull/7387)
Testing Procedure:
- I ran a custom autotester with this test script:
`echo '{"annotations": [{"filename": "submission.py", "content": "Message 1!", "line_start": 3, "line_end": 5, "column_start": 1, "column_end": 4}, {"filename": "submission.py", "content": "Message 2!", "line_start": 6, "line_end": 9, "column_start": 1, "column_end": 4}]} {"name": "Custom Test 4", "output": "Perfect!", "marks_earned": 100, "marks_total": 100, "status": "pass", "time": 1} {"overall_comment": "Test 4 Comment 1!"} {"tags": [{"name": "Tag1", …
> Support for tags and overall comments in test group results

- Changelog.md
- server/autotest_server/testers/jupyter/setup.py
- server/autotest_server/testers/py/setup.py
- server/autotest_server/testers/pyta/setup.py
Display Python package installation stderr if the installation fails. This is done for testers Py, PyTA and Jypyter.
Screenshot 1: I made a syntax error for the option --clear to have only 1 hyphen when creating the venv
Screenshot 2: in the requirements file, I entered an invalid value of "test=" when installing python packages
> Improve display of Python package installation errors when creating environment

- README.md
- compose.yaml
- server/.gitignore
- server/autotest_server/settings.yml
- server/install.py
- server/start_stop.py
**Description:**
We want to have logging for supervisor's child process logs for both stderr and stdout.  These logs will be stored under the folder `supervisor_child_log`. I have set the log file rotation to a file size of 1MB with 10 backups. e.g.:
```
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
```
Here is a screenshot of how it looks like on my local server's workspace docker volume in regards to the generated log files:
> Logging supervisor's child process logs

- Changelog.md
- client/autotest_client/__init__.py
When the setting up of the test environment is still in progress, currently we would send an exception back to the MarkUs application to notify the user. However, we rather receive an http response instead of an exception, this way we can act accordingly with regards to the http response code. 
This PR needs to be deployed together with the MarkUs PR as they work hand in hand. 
MarkUs PR: https://github.com/MarkUsProject/Markus/pull/7445
> Update "setting up test environment" message with http response

- .pre-commit-config.yaml
- Changelog.md
- server/autotest_server/__init__.py
This PR improves error reporting by changing how tester exceptions are handled. Previously, caught exceptions were converted to strings before being added to the test result, which often produced unhelpful error messages (e.g., KeyError would report just the key itself).
This PR introduces a way to handle exceptions with user-friendly messages using assert. Developers are expected to assert conditions that, if violated, will cause the autotester to fail:
- Assertion errors are caught higher up, and the assertion error message (if provided) will be reported in the test result.
- For other types of exceptions, the full stack trace will be reported in the test result instead.
In both cases, the full stack trace is printed.
> Improve error reporting with handled assertion errors

- Changelog.md
- server/autotest_server/testers/py/py_tester.py
- server/autotest_server/testers/tester.py
This pull requests updates the Python tester to add four new `pytest` custom markers:
- `markus_tag` (for adding tags to a submission)
- `markus_annotation` (for adding annotations to a submission)
- `markus_overall_comment` (for adding overall comments to a submission)
- `markus_message` (for displaying messages in the test output)
The first two build on https://github.com/MarkUsProject/markus-autotesting/pull/582 and https://github.com/MarkUsProject/Markus/pull/7387. The third takes advantage of existing autotester functionality (which is currently only used by the PyTA tester).
The fourth modifies the current Python tester behaviour: currently, the only test output shown to students is error messages. The new marker allows the instructor to provide custom messages that are displayed to …
> Added custom pytest markers to Python tester to record MarkUs metadata

- Changelog.md
- server/autotest_server/__init__.py
- server/autotest_server/tests/test_autotest_server.py
This pull request includes changes to improve settings error handling in the `server/autotest_server` module. The most important change is adding assertions to check for errors in test settings (this stop the autotester from running tests if there are errors in test settings.)
- Added assertions to check for errors in test settings and environment status before running tests.
- Modified the `update_test_settings` to move setting the `_files` key closer to where the value for `_files` in first created. 
- Added unit tests for `run_test` to ensure it handles settings errors.
> Stop the autotester from running tests if there are errors in test settings

- Changelog.md
- client/.dockerfiles/Dockerfile
- client/.dockerfiles/entrypoint-dev-deps-updater.sh
- client/requirements.txt
- compose.yaml
- server/.dockerfiles/Dockerfile
- server/.dockerfiles/cmd-dev.sh
- server/.dockerfiles/entrypoint-dev-deps-updater.sh
- server/requirements.txt
Also drop support for Python 3.8 and switch to Python 3.13 in development.
> Update Docker config to install dependencies in separate service.

- compose.yaml
This pull request includes a small change to the `compose.yaml` file. The change updates the `ports` configuration for the `redis` service to explicitly map the container port `6379` to the host port `6379`. Without this change any connections coming from outside the docker container will be refused, making it impossible to interact with redis using external tools.
> Quote redis port mapping in compose.yaml

- Changelog.md
- server/autotest_server/testers/r/lib/r_tester.R
- server/autotest_server/testers/r/r_tester.py
- server/autotest_server/tests/testers/r/test_r_tester.py
This PR adds support for `markus_tag`, `markus_annotation`, and `markus_overall_comments` metadata to the R tester.
This is analogous to https://github.com/MarkUsProject/markus-autotesting/pull/592.
> Updated R tester to support MarkUs test metadata

- Changelog.md
- server/autotest_server/testers/py/py_tester.py
This PR builds on #592 to add two new custom pytest marks: `markus_marks_earned` and `markus_marks_total`, which allow the user to specify mark values for individual test cases.
This PR only affects the Python tester and the `pytest` runner (not `unittest`).
> Added MarkUs metadata for test marks to Python tester

- Changelog.md
- server/autotest_server/testers/r/r_tester.py
Previously, the R tester only displays test messages when the test is not a success. Because test successes may also have messages, I've modified the tester to always include messages when they are present.
> Ensured R tester always displays test messages

- Changelog.md
- server/autotest_server/testers/ai/ai_tester.py
Previously, when the submission file wasn't found, the AI tester reported `"Student included the text 'NO_EXTERNAL_AI_FEEDBACK' in their submission file. No AI feedback generated."`
This was due to the implementation of the `AITester._term_in_file` method, which returned `True` when the file was not found. I modified the implementation to raise a `FileNotFoundError` instead.
> Fixed AI tester to report error when the specified submission file is not found
